// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// saucy_int
Rcpp::List saucy_int(std::string filename, std::string mode, int timeout, int rpt);
RcppExport SEXP _saucy_saucy_int(SEXP filenameSEXP, SEXP modeSEXP, SEXP timeoutSEXP, SEXP rptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< int >::type timeout(timeoutSEXP);
    Rcpp::traits::input_parameter< int >::type rpt(rptSEXP);
    rcpp_result_gen = Rcpp::wrap(saucy_int(filename, mode, timeout, rpt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_saucy_saucy_int", (DL_FUNC) &_saucy_saucy_int, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_saucy(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
