# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

saucy_int <- function(filename, mode, timeout, rpt) {
    .Call('_saucy_saucy_int', PACKAGE = 'saucy', filename, mode, timeout, rpt)
}

shatter_int <- function(filename, sbp_file, gfile) {
    .Call('_saucy_shatter_int', PACKAGE = 'saucy', filename, sbp_file, gfile)
}

